/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'MyFlutterApp';
  static const String _kFontPkg = null;

  static const IconData home = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agents = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData catalogue = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData data_sheet = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contract = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData certificate = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customers = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData avatar = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warehouse = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData show_price = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calculator = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_menu = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
